on: push

jobs:
  build:
    runs-on: self-hosted
    container:
      image: node:14.15.0-alpine3.12

    steps:
      - uses: actions/checkout@v2
      - name: Log the node version
        run: |
          node -v
          cat /etc/os-release
