on: push

permissions: read-all

jobs:
  pre-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello World\n"

  build:
    runs-on: ubuntu-latest
    needs: pre-build
    container:
      image: node:14.15.0-alpine3.12

    steps:
      - uses: actions/checkout@v2
      - name: Log the node version
        run: |
          node -v
          cat /etc/os-release
